# Site settings
title: Viol Making Symposium
email: info@violmaking.org
description: > # this means to ignore newlines until "baseurl:"
   A one-day symposium about making the Viola da Gamba or Viol, hosted 
   at West Dean College in Sussex, featuring speakers on aspects of viol construction, restoration, 
   decoration and setup
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://violmaking.org" # the base hostname & protocol for your site
twitter_username: 
theme: minima

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext